# Generated by Django 4.1 on 2022-08-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
