# Generated by Django 4.1 on 2022-08-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_subscribe_reportuser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('subscribed_by', 'subscribed_to')},
        ),
    ]
