# Generated by Django 4.1 on 2022-08-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_subscribe_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportuser',
            name='report_reason',
            field=models.TextField(blank=True),
        ),
    ]
